---
- name: Run 'show run' on Cisco Switch
  hosts: cisco_switches
  gather_facts: no
  
  vars:
    ansible_connection: network_cli
    ansible_network_os: ios
    ansible_become: yes
    ansible_become_method: enable

  tasks:
    - name: Execute 'show run' command
      cisco.ios.ios_command:
        commands:
          - show run
      register: output

    - name: Display the output
      debug:
        var: output.stdout_lines
